"""
Subject- / session-independent train/validation splits for MRANC processed data.

Requires window_groups.npy alongside mix.npy (generated by preprocessing scripts).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Literal

import numpy as np

from paths import (
    ARTIFACT_BENCHMARK_PROCESSED,
    DATASET_DIRS,
    DEFAULT_SPLIT_SEED,
    DEFAULT_VAL_FRACTION,
    PROCESSED_CLINICAL,
    PROCESSED_DEAP,
    PROCESSED_SEED,
)

logger = logging.getLogger(__name__)

SplitPolicy = Literal["group", "contiguous"]
WINDOW_GROUPS_FILENAME = "window_groups.npy"
SPLIT_POLICY_FILENAME = "split_policy.json"

DATASET_SPLIT_POLICY: dict[str, SplitPolicy] = {
    "deap": "group",
    "seed": "group",
    "clinical": "group",
    "artifact_benchmark": "contiguous",
}


def resolve_split_policy(data_dir: Path, dataset: str | None = None) -> SplitPolicy:
    policy_path = data_dir / SPLIT_POLICY_FILENAME
    if policy_path.is_file():
        try:
            data = json.loads(policy_path.read_text(encoding="utf-8"))
            policy = data.get("split_policy")
            if policy in ("group", "contiguous"):
                return policy  # type: ignore[return-value]
        except (json.JSONDecodeError, OSError):
            pass
    if dataset is not None and dataset in DATASET_SPLIT_POLICY:
        return DATASET_SPLIT_POLICY[dataset]
    return "group"


def load_window_groups(data_dir: str | Path) -> np.ndarray:
    data_dir = Path(data_dir)
    groups_path = data_dir / WINDOW_GROUPS_FILENAME
    mix_path = data_dir / "mix.npy"
    if not mix_path.is_file():
        raise FileNotFoundError(f"Missing mix.npy in {data_dir}")
    if not groups_path.is_file():
        raise FileNotFoundError(
            f"Missing {WINDOW_GROUPS_FILENAME} in {data_dir}. "
            "Re-run the dataset preprocessing script to generate subject/session groups."
        )
    groups = np.load(groups_path)
    if groups.ndim != 1:
        raise ValueError(f"{groups_path}: expected 1D array, got shape {groups.shape}")
    n_mix = int(np.load(mix_path, mmap_mode="r").shape[0])
    if groups.shape[0] != n_mix:
        raise ValueError(
            f"{groups_path}: length {groups.shape[0]} != mix.npy windows {n_mix}"
        )
    return groups.astype(np.int64, copy=False)


def _groups_for_indices(group_ids: np.ndarray, indices: np.ndarray) -> set[int]:
    return set(int(g) for g in np.unique(group_ids[indices]))


def assert_disjoint_groups(
    group_ids: np.ndarray,
    train_idx: np.ndarray,
    val_idx: np.ndarray,
    *,
    split_policy: SplitPolicy = "group",
) -> None:
    train_set = set(int(i) for i in train_idx)
    val_set = set(int(i) for i in val_idx)
    overlap_idx = train_set & val_set
    if overlap_idx:
        raise ValueError(f"Train/val window index overlap: {sorted(overlap_idx)[:10]}")

    if split_policy == "contiguous":
        return

    train_groups = _groups_for_indices(group_ids, train_idx)
    val_groups = _groups_for_indices(group_ids, val_idx)
    group_overlap = train_groups & val_groups
    if group_overlap:
        raise ValueError(
            "Subject/session group leakage: train and val share groups "
            f"{sorted(group_overlap)}"
        )


def audit_split_leakage(
    group_ids: np.ndarray,
    train_idx: np.ndarray,
    val_idx: np.ndarray,
    *,
    split_policy: SplitPolicy = "group",
    label: str = "",
) -> None:
    assert_disjoint_groups(
        group_ids, train_idx, val_idx, split_policy=split_policy
    )
    prefix = f"[split-audit{(' ' + label) if label else ''}]"
    train_groups = _groups_for_indices(group_ids, train_idx)
    val_groups = _groups_for_indices(group_ids, val_idx)
    intersection = train_groups & val_groups
    logger.info(
        "%s train_windows=%d val_windows=%d train_groups=%d val_groups=%d "
        "intersection=%s OK",
        prefix,
        len(train_idx),
        len(val_idx),
        len(train_groups),
        len(val_groups),
        intersection if split_policy != "contiguous" else "N/A (contiguous)",
    )
    if split_policy == "contiguous":
        print(
            f"{prefix} contiguous temporal holdout OK | "
            f"train_windows={len(train_idx)} val_windows={len(val_idx)}"
        )
    else:
        print(
            f"{prefix} train_subjects.intersection(val_subjects) = {intersection} "
            f"(train_groups={len(train_groups)}, val_groups={len(val_groups)})"
        )


def group_train_val_indices(
    group_ids: np.ndarray,
    val_fraction: float,
    seed: int,
    *,
    split_policy: SplitPolicy = "group",
) -> tuple[np.ndarray, np.ndarray]:
    if not 0.0 < val_fraction < 1.0:
        raise ValueError(f"val_fraction must be in (0, 1), got {val_fraction}")

    n_total = int(group_ids.shape[0])
    if n_total < 2:
        raise ValueError(f"Need at least 2 windows for a split, got {n_total}")

    n_val = max(1, int(n_total * val_fraction))
    n_train = n_total - n_val
    if n_train < 1:
        raise ValueError(
            f"val_fraction={val_fraction} leaves no training windows (n_total={n_total})"
        )

    if split_policy == "contiguous":
        train_idx = np.arange(0, n_train, dtype=np.int64)
        val_idx = np.arange(n_train, n_total, dtype=np.int64)
        assert_disjoint_groups(group_ids, train_idx, val_idx, split_policy=split_policy)
        return train_idx, val_idx

    unique_groups = np.unique(group_ids)
    rng = np.random.default_rng(seed)
    shuffled = list(rng.permutation(unique_groups))

    val_groups: list[int] = []
    val_window_count = 0
    target_val = n_val

    for group in shuffled:
        if val_window_count >= target_val and len(val_groups) >= 1:
            break
        val_groups.append(int(group))
        val_window_count += int(np.sum(group_ids == group))

    if not val_groups:
        val_groups = [int(shuffled[0])]

    val_group_set = set(val_groups)
    val_mask = np.isin(group_ids, list(val_group_set))
    val_idx = np.flatnonzero(val_mask).astype(np.int64)
    train_idx = np.flatnonzero(~val_mask).astype(np.int64)

    if train_idx.size == 0:
        raise ValueError(
            "Group split assigned all windows to validation; "
            "reduce val_fraction or add more groups."
        )

    assert_disjoint_groups(group_ids, train_idx, val_idx, split_policy=split_policy)
    return train_idx, val_idx


def train_val_indices_for_dir(
    data_dir: str | Path,
    val_fraction: float = DEFAULT_VAL_FRACTION,
    split_seed: int = DEFAULT_SPLIT_SEED,
    *,
    dataset: str | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, SplitPolicy]:
    data_dir = Path(data_dir)
    group_ids = load_window_groups(data_dir)
    policy = resolve_split_policy(data_dir, dataset=dataset)
    train_idx, val_idx = group_train_val_indices(
        group_ids, val_fraction, split_seed, split_policy=policy
    )
    return train_idx, val_idx, group_ids, policy


def val_indices(
    n_total: int,
    val_fraction: float = DEFAULT_VAL_FRACTION,
    split_seed: int = DEFAULT_SPLIT_SEED,
    *,
    data_dir: str | Path | None = None,
    dataset: str | None = None,
) -> list[int]:
    if data_dir is None:
        if dataset is None or dataset not in DATASET_DIRS:
            raise ValueError(
                "val_indices requires data_dir or a known dataset name "
                f"(got dataset={dataset!r})"
            )
        data_dir = DATASET_DIRS[dataset]
    _, val_idx, _, _ = train_val_indices_for_dir(
        data_dir,
        val_fraction=val_fraction,
        split_seed=split_seed,
        dataset=dataset,
    )
    return val_idx.tolist()


def train_indices(
    n_total: int,
    val_fraction: float = DEFAULT_VAL_FRACTION,
    split_seed: int = DEFAULT_SPLIT_SEED,
    *,
    data_dir: str | Path | None = None,
    dataset: str | None = None,
) -> list[int]:
    if data_dir is None:
        if dataset is None or dataset not in DATASET_DIRS:
            raise ValueError(
                "train_indices requires data_dir or a known dataset name "
                f"(got dataset={dataset!r})"
            )
        data_dir = DATASET_DIRS[dataset]
    train_idx, _, _, _ = train_val_indices_for_dir(
        data_dir,
        val_fraction=val_fraction,
        split_seed=split_seed,
        dataset=dataset,
    )
    return train_idx.tolist()


def audit_dataset_split(
    dataset: str,
    val_fraction: float = DEFAULT_VAL_FRACTION,
    split_seed: int = DEFAULT_SPLIT_SEED,
    data_dir: str | Path | None = None,
) -> None:
    if data_dir is None:
        if dataset not in DATASET_DIRS:
            raise ValueError(f"Unknown dataset: {dataset}")
        data_dir = DATASET_DIRS[dataset]
    train_idx, val_idx, group_ids, policy = train_val_indices_for_dir(
        data_dir,
        val_fraction=val_fraction,
        split_seed=split_seed,
        dataset=dataset,
    )
    audit_split_leakage(
        group_ids, train_idx, val_idx, split_policy=policy, label=dataset
    )


ALL_SPLIT_DATASETS = ("deap", "seed", "clinical", "artifact_benchmark")
